### ISSUE TITLE
Reverse Swaps: verify locked on-chain amount = expected amount

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#105]
Follow-up of https://github.com/BoltzExchange/boltz-webapp-3.0/issues/82. This issue is about webapp verifying make sure on-chain amount is the one used `/createswap` **before** claiming. Not trivial because webapp would need to query the mempool (0-conf swaps), ideally also double check that RBF is not enabled or query the chain to do so. Needs to be via 3rd party mempool api.

- [ ] add to backend docs

**Comment by michael1011** [comment]
That's been implemented for a while already
