### ISSUE TITLE
Browser Autotranslation issues

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-web-app#112]
Wrong refund ETA - Looks like Edge mobile with translation enabled:

![image](https://github.com/BoltzExchange/boltz-webapp-3.0/assets/8138838/a99bdae6-702d-4a01-ada5-f2fd2fa8c30b)

**Comment by armurbalda** [comment]
Another thing that seems related: min max shows 0

![20230706_082720](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/21c363dd-536d-4acf-93f6-48123095071f)

**Comment by dni** [comment]
i think there is nothing we can do about it? any ideas, its a browser "feature"

**Comment by armurbalda** [comment]
Can you carefully check the difference of the variables for network and boltz fee in satoshis which edge could retrieve successfully whereas the % fee and min/max amounts not?
