### ISSUE TITLE
Move blocking notifications into swap button

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#147]
Blocking errors (user needs to act to resolve) like these are not in the focus area on higher resolution desktop AND dissapear too fast to be read and understood. Invoice already exists, miner fees updated etc. Don't think all of them can be moved into the swap button (`network fees updated`), so will need to try sth else.

![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/2f7eeaa6-ef4f-4a41-a441-d74aa0a26ba0)

**Comment by dni** [comment]
resolved?
