### ISSUE TITLE
[UX Revamp] Error message in Swap Button

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#162]
All errors that occur in a "swap button greyed out" state should have error message WITHIN swap button since there is nothing that can trigger a tooltips-style error message. E.g. here it should tell me what's wrong with my invoice (wrong amount)
![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/6be97073-6129-4dce-9b4d-53542443b54a)

**Comment by kilrau** [comment]
WILL PROVIDE WIREFRAME

**Comment by dni** [comment]
i think i dont need any wireframes for that

**Comment by kilrau** [comment]
Done in https://github.com/BoltzExchange/boltz-web-app/pull/317
