### ISSUE TITLE
[Normal Swaps] Show on-chain amount

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#167]
Show exact on-chain amount to be sent as instruction sentence similar to

![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/775bfa82-0fed-4be8-b0d1-8773347b74a7)

We still have users sending wrong amount (e.g. ignoring fees) causing swaps to fail. Also some just don't want to use the copy buttons.

**Comment by armurbalda** [comment]
Several other users reported this, closing https://github.com/BoltzExchange/boltz-web-app/issues/153 as duplicate

**Comment by dni** [comment]
![screenshot-1687878798](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/f3e8a26b-e53e-451a-81e4-54c23c959eb8)
