### ISSUE TITLE
Fetching swap status misses loading indicator

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#169]
On slower connections like Tor one notices this

![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/385afccc-b365-417f-8f39-cb8e0cb83485)

**Comment by dni** [comment]
is it ok just to put status (loading) ?

**Comment by armurbalda** [comment]
Let's decide for something now and then consistently apply it everywhere we are facing this issue. A static `Loading` doesn't cut it imo , it should be *moving* to give user assurance it's actually doing something. Simplest I could think of is this animation:
`.`
`. .`
`. . .`
`.`

**Comment by dni** [comment]
we could just use the animation we have for mempool

**Comment by armurbalda** [comment]
Jup I was about to suggest that but was not sure if it'll look good that small. Try!

**Comment by michael1011** [comment]
Maybe don't put the animation in place of the loading text put instead of the text I put underneath
