### ISSUE TITLE
[Mobile] Swap Box should have border

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#179]
Swap box on mobile should have a border .. to be a box

![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/6e51a8ef-eb14-4c6a-b327-bc6a24952171)

Based on [user feedback](https://snort.social/e/nevent1qqsy036r0fl07gkxnss0m6jlve2pmlj7a8tnmgnvpe8e4qfazm98cespremhxue69uhkummnw3ez6ur4vgh8wetvd3hhyer9wghxuet59uq3qamnwvaz7tmwdaehgu3wd4hk6tcpzamhxue69uhhyetvv9ujumn0wd68ytnzv9hxgtcpr4mhxue69uhkummnw3ezucnfw33k76twv4ezuum0vd5kzmp0v40jwf).

**Comment by dni** [comment]
are you sure i think it looks good

**Comment by armurbalda** [comment]
What we can do is do https://github.com/BoltzExchange/boltz-web-app/issues/193 first and see how it looks

**Comment by dni** [comment]
did this one resolve?

**Comment by armurbalda** [comment]
Still think with border looks better but well not important enough to keep this issue open. Closing.
