### ISSUE TITLE
[Landing Page] Swap Box - only fade out if space is not enough

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#180]
If screen space is enough to show all of this, don't fade out swap box:

![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/a44a7c2a-2a07-49a1-a73d-8d98d3f629ea)

In all other cases dynamically fade out to always make everything including button fit. On very small screens there might not be much of the swap box left and that's fine.

Also based on user feedback:
- https://snort.social/e/nevent1qqsrlmx666cdvhgrh5y327d89n7yld4r6d0erwu6khqpwa5jyz3v9hqpr4mhxue69uhkummnw3ezucnfw33k76twv4ezuum0vd5kzmp0qyv8wumn8ghj7mn0wd68ytnxd46zuamf0ghxy6t69uywq82g
- https://snort.social/e/nevent1qqsyx4483dgd6cn47gw9cgay7nh7a8qxh3wgxxh9tcqldfpkq0ghpxgpzamhxue69uhhyetvv9ujumn0wd68ytnzv9hxgtcuvtkly

**Comment by dni** [comment]
i dont agree with this, i think it is fine as it is.
