### ISSUE TITLE
Claim swaps on any page

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#190]
Right now claiming is only triggered when one visits the /swapID subpage, webapp should detect claimable swaps and claim on any page to avoid this:
![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/73d913d9-98b2-435f-835e-5613c1696abb)

**Comment by dni** [comment]
not sure if i like that, to magically claim the swaps in the background, i feel like that is kind of confusing aswell. maybe a info popup or notification that tell you a swap is claimable ```click here```  and it just redirect you into the normal swap flow again.

and/or what if we add a browser warning when someone wants to leave the swap flow before it is finished, ```warning! dont leave this page else your swap will not be claimed```

**Comment by michael1011** [comment]
> not sure if i like that, to magically claim the swaps in the background, i feel like that is kind of confusing aswell

Swaps from onchain to lightning also settle magically in the background with being on the page

> maybe a info popup or notification that tell you a swap is claimable click here and it just redirect you into the normal swap flow again.

Let's not get into popups. That will become insanely messy

**Comment by armurbalda** [comment]
> i feel like that is kind of confusing aswell.

What? It's not confusing if a swap completes successfully no matter where I am on the page. And again this was an actual user issue.

> Swaps from onchain to lightning also settle magically in the background without being on the page

Look at that. Not confusing at all.

> maybe a info popup or notification that tell you a swap is claimable click here and it just redirect you into the normal swap flow again
> and/or what if we add a browser warning when someone wants to leave the swap flow before it is finished, warning! dont leave this page else your swap will not be claimed

Just.. no. Michael and I align so let's do it!
