### ISSUE TITLE
Avoid blank space above swap box on mobile if not all elements fit

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#193]
![Screenshot from 2023-07-11 11-55-08](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/90a58355-3b36-47e2-9be5-f186d1a8e8ca)

**Comment by dni** [comment]
its because of the glow effect on frontpage. should we remove the glow for mobiles altogether?

**Comment by michael1011** [comment]
> its because of the glow effect on frontpage. should we remove the glow for mobiles altogether?

+1 for that

**Comment by armurbalda** [comment]
+1

**Comment by dni** [comment]
![screenshot-1689665629](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/0c37438a-de24-4d9b-b881-efb03ea872fb)
