### ISSUE TITLE
Hash change causes "network fees were updated" when they were in fact not updated

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#197]
Especially relevant for Liquid Swaps since fees practically never change there, but notification pops up because mainchain fees changed. Reason: pairhash contains fees for more than relevant assets

Diffuculty: we don't know who is using it so me might break an implementation if we change it in backend. So let's try to do it in frontend.

Another thing to consider speaking *for* a change in backend: e.g. Liquid wallets using the pairhash feature the same way will face the same issue

**Comment by armurbalda** [comment]
As just discussed: web app additionally checks if on-chain fees *really* changed when pairhash changes and only then shows error to check fees again

**Comment by kilrau** [comment]
See[ my comment](https://github.com/BoltzExchange/boltz-backend/issues/390#issuecomment-1742857942) why this double check from web app is highly needed - there is no short-term fix from backend side
