### ISSUE TITLE
Warning: "Your invoice is expiring soon"

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#198]
Web App checks invoice expiry. If invoice expiry is less than 24h, we show a warning that user has to click away.

Option 1: "Your invoice expiry is *invoice expiry time in seconds* minutes, make sure to complete swap before" - easy
Option 2: "Your invoice is expiring in 4:59 minutes (current time - (timestamp+expiry)), make sure to complete swap before" - better
Option 3: "Your invoice is expiring in 4:59 minutes (current time - (timestamp+expiry)), we highly recommend setting invoice expiry to 24h or higher to prevent your swap from failing.

a) change invoice b) keep invoice as-is

**Comment by kilrau** [comment]
Just had such a case again, I'll draw sth up

**Comment by kilrau** [comment]
Replaced by https://github.com/BoltzExchange/boltz-web-app/issues/321
