### ISSUE TITLE
Loading Animation

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#201]
First load on slow connections like with TOR can take a while, let's have a very simple (needs to be super light to load) loading animation with our logo slowly beating, compare https://opendex.app/

![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/66c222bf-90bc-46c2-b08b-613fd8c9fe1b)

**Comment by michael1011** [comment]
> loading animation with our logo slowly beating

The "slowly beating" doesn't look good. So @dni and I agreed to just put the logo

**Comment by armurbalda** [comment]
ayt
