### ISSUE TITLE
[Normal Swaps] Make clear when we don't accept 0-conf, make swap expiry clear, suggest miner fee

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#204]
We had numerous support cases recently where folks submitted their on-chain txes with ultra-low fees, sometimes even by accident not double-checking the horrendous fee estimations of their wallets. We want to bring "swap expires within 24h" and "check your miner fee" into awareness and give concrete fee suggestions. I suggest mempool.space's low, mid, high prio

![Screenshot from 2023-07-20 10-32-24](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/3ac94501-9d0e-4855-9995-eb90b3a9330b)

Additionally we should take invoice expiry into account, to not only [warn in case of super short expiries](https://github.com/BoltzExchange/boltz-web-app/issues/198) but to e.g. only display high prio fee if invoice expires within one hour, all three only if invoice expires in 24h or more.

Todo: mockup

**Comment by michael1011** [comment]
> e.g. only display high prio fee if invoice expires within one hour, all three only if invoice expires in 24h or more.

Not a fan of this. We shouldn't clutter that page because someone messed it up once

**Comment by armurbalda** [comment]
users constantly miscalculate on-chain fees
