### ISSUE TITLE
[Refund] Refund button needs success message

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#206]
Green tooltips "success" enough for now, we'll design a proper success state message later. As of now it doesn't say anything just mempool link button appears

**Comment by dni** [comment]
there is a green success notification popping up when the refund was successful.

for this edgecase uploading the json without having it in localstorage we have no success page (i added a success message, in case anyone misses the notification), for the proper flow via localstorage there is a proper success page.
