### ISSUE TITLE
Keep amounts on swap direction change

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#212]
Avoid ever decreasing amounts on direction change by keeping amounts 1:1 as-is when direction of swap is changed.

[Screencast from 06-20-2023 05:32:21 PM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/25886821-785b-4f49-8cf1-2dc411f09bb6)

**Comment by michael1011** [comment]
Keep which amount? Send or receive? One has to change on direction switch

**Comment by armurbalda** [comment]
True, fees are different. Keeping send amount makes sense I think.
