### ISSUE TITLE
Language selector fixes

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#214]
The [language selector](https://github.com/BoltzExchange/boltz-web-app/pull/184) needs some adjustments:
- [x] #217
- [x] https://github.com/BoltzExchange/boltz-web-app/pull/218 made languages appear appear in their native form: English, 日本語, Deutsch, Español in the dropdown. TODO: make it part of localization in `i18n.js`
- [x] default to English if string is missing
- [x] ~Not sure if this is easy but it's not great that the language selector position jumps because e.g. Japanese needs less space then other languages. Is it possible to assign a fixed min width for header menu items? @dni If a language needs *more* space then the header menu still moves, but at least it's limited.~

**Comment by dni** [comment]
can you explain why we need 2 clicks? i prefer it as hover.

it was a fixed we decided we make it centered. but i think now with using the globe icon it as quite good as is i don't mind the size differences.

**Comment by armurbalda** [comment]
> can you explain why we need 2 clicks? i prefer it as hover.

One to open the language dropdown, one to select the language. The hover already feels very fragile on Desktop, and doesn't work at all on mobile. Right now when I am in Japanese on mobile and I click the globe I always chose English, no way to avoid it. Please try it yourself: https://webapp-d75vjw1qq-boltz.vercel.app/

> i don't mind the size differences.

It's not about the size difference, it's about the header menu jumping. Any idea how to avoid it?
