### ISSUE TITLE
WebLN enable() should not expect an object?

### ISSUE THREAD

**Issue by otech47** [BoltzExchange/boltz-web-app#229]
According to the spec at webln.guide the [enable](https://www.webln.guide/building-lightning-apps/webln-reference/webln.enable) function has a return type of `void`

boltz.exchange has 2 instances calling `window.webln.enable()` and both are expecting it to return an object with a `enabled` field that must be truthy in order for webLN to proceed and work properly

Seems Alby as a WebLN provider is also deviating from this spec since the webln object injected by Alby has an `enable` function that does not have a `void` return type, which is probably why the logic below was written this way

![Screenshot 2023-07-27 at 1 44 10 PM](https://github.com/BoltzExchange/boltz-web-app/assets/4914611/88ad2486-9c02-4d70-a53b-84dee71a050b)

Not sure if the spec should change or this implementation should change but WebLN providers who implement `enable` according to the spec will not be compatible with boltz.exchange due to this inconsistency

**Comment by humansinstitute** [comment]
Hi All - when I test this in Fedi App I'm still getting failures trying to pay via webLN is this deployed on bolts.exchange?
