### ISSUE TITLE
Alignment of icons in history

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-web-app#291]
![image](https://github.com/BoltzExchange/boltz-web-app/assets/8138838/4d913fc2-aaa5-48ae-be6c-9a914ed9d14e)

The Lightning icon seems to have more margin than the others

**Comment by dni** [comment]
hm, the history is kind of centered, and the only difference is probably the swap id and date
![screenshot-1697530163](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/e21cc709-a3c0-4765-9781-8b5b89de08a2)

not sure if i like it better if its left aligned?

**Comment by michael1011** [comment]
it's better aligned imho

@kilrau ?

**Comment by kilrau** [comment]
Yes, better left aligned!
