### ISSUE TITLE
Lnurl: allow new attempt after "failed to fetch"

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#294]
After this:
![Screenshot from 2023-10-23 16-07-28](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/1c23ceb6-7701-4e29-998a-7e044f718dbb)

Web App should re-enable the "Create Atomic Swap" button once at least one char was deleted/added and the content passes pattern validation:
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/40faf9e1-8afb-4e56-86b3-4deac86acd5e)

Otherwise the only fix is to refresh of the site after a typo in a lightning address.

Bonus points: `Failed to fetch` -> `Failed to fetch invoice. Please make sure to enter a valid lnurl/lightning address!`

**Comment by dni** [comment]
tested this on latest, and it is fixed! reopen pls if not.

**Comment by kilrau** [comment]
It is fixed.
