### ISSUE TITLE
Add "Use Case" section to landing page

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#297]
We'd want to add a section about "Use Cases" - what one can do with Boltz - with the following content to the landing page.

🫰 Reliably cheap LN channel rebalancing
❄️ DCAing from LN into cold storage
👨‍💻 Increase coin privacy from CEX purchases

Probably adding it as one of these boxes is a good idea. But need to try what looks good.
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/dfc98a90-47a0-4d04-8142-164b94191c56)

**Comment by lenekin** [comment]
Do you want it as one or three boxes?

**Comment by kilrau** [comment]
> Do you want it as one or three boxes?

One box with the three bullet points

**Comment by lenekin** [comment]
![grafik](https://github.com/BoltzExchange/boltz-web-app/assets/149952459/d020d364-e75c-440b-acad-42c309a9d7c8)
Like this?

**Comment by lenekin** [comment]
![grafik](https://github.com/BoltzExchange/boltz-web-app/assets/149952459/ed8d65e1-7670-4fc5-bf8f-1f7217374b99)
Do you want the Text left-aligned or centered?

**Comment by kilrau** [comment]
Use Case**s**

well I'd leave it centered but would love to preven that line break somehow. Anyhow, could you open a PR with your changes?

**Comment by lenekin** [comment]
Made a PR, do you want anything changed?

**Comment by kilrau** [comment]
> Made a PR, do you want anything changed?

https://github.com/BoltzExchange/boltz-web-app/pull/337#pullrequestreview-1750257671
