### ISSUE TITLE
Embed: add url parameters

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#334]
URL parameters (all optional, we default):

- `pairID`: (default: `BTC/BTC`)
- `type`: (default: `reversesubmarine`)
- `bip21`: Overwrites parameters above the same way web app swap box does. We only need address & optional amount. Let's not forget `liquidnetwork:`
- `invoice`: overwrites parameters above. (no default)
- `referral`: partner referral id (default: boltz_webapp_embed)
- `css`: style sheet for swap box customization

_Originally posted by @kilrau in https://github.com/BoltzExchange/boltz-web-app/issues/328#issuecomment-1820505661_

**Comment by tohrxyz** [comment]
@kilrau hey, is this restricted for iframe embeds or can i use this somehow to make a URL that would pre-fill values?

like let's say i want to have lightning -> l-btc with destination address prefilled from url ?

is this possible?

**Comment by dni** [comment]
yes, this should be possible! working on it

**Comment by dni** [comment]
i have created an example page for embedding where you can see which is currently possible. https://dni.github.io/boltz-webapp-embed/

with this branch https://github.com/BoltzExchange/boltz-web-app/pull/547
