### ISSUE TITLE
UX: Add swap success sound

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#338]
compare mempool.space's iconic sounds

**Comment by kilrau** [comment]
Come on mempool's sounds are awesome. I absolutely love them and associate them with sth positive: transaction included in a block, address has a new incoming transaction etc. Swap success sound is absolutely sth along these lines PLUS it'll get your attention if the swap tab is currently not in foreground.

**Comment by dni** [comment]
lets try it :)
