### ISSUE TITLE
UX: Misc Improvements

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#339]
- Main idea: "Instructions as titles" as previously done in Figma
- ~Orignal issue: https://github.com/BoltzExchange/boltz-web-app/issues/220~
- Additional things to consider: show preimage as proof of Payment for Normal swaps? See discussion at https://discord.com/channels/547454030801272832/714342346568892487/1164762317439914085
- ~Send to for paying a ln invoice sounds just wrong, copy button is missing -> not discoverable one can click to copy the invoice~ ![Image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/e47d0935-e84c-46f2-8f9a-45e17d74ec0a)
- ~Move denomination swtich to upper right to be present whenever therer are amounts just like in PRD~
- "locked amount is less than expexted amount" -> "you sent amount too little"
- Include still releveant and missing things from PRD
- add "sats/btc" after all amounts, still missing in some pages
- make clear reverse swaps are automatically refunded, add invoice expiry as estimated time
- ~people don't get the refund page~
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/e1cee7e5-eacd-4fe3-82b2-ccbc799fea2d)

**Comment by dni** [comment]
can you revaluate this issue, not sure how i can move on with any of those points.

**Comment by kilrau** [comment]
This issue is not ready yet

**Comment by dni** [comment]
ok, but this issue still has `P1` :)

**Comment by kilrau** [comment]
Extracted showing the preimage into [a separate issue](https://github.com/BoltzExchange/boltz-web-app/issues/732) and closing here.
