### ISSUE TITLE
Handle backend error `"error":"invoice expiry too short"` correctly

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#359]
EDIT: this was implemented in [backend](https://github.com/BoltzExchange/boltz-backend/pull/498) and web app just has to handle it properly

**Comment by dni** [comment]
we will get the error message from the backend, see screenshot. is that enough?

![screenshot-1711523265](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/38b38366-4e38-4be2-805d-aa51e5710f60)

**Comment by kilrau** [comment]
Yes that's perfect
