### ISSUE TITLE
UX: Switch assets based on address/invoice input

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-web-app#374]
When a Liquid address is entered/scanned, the frontend should switch the receiving symbol the L-BTC. Similar concept for Bitcoin addresses and lightning invoices/lnurls/sat domains

**Comment by kilrau** [comment]
Also gets rid of this error where web app should revalidate my liquid address when I am switchin to Liquid:
[Screencast from 01-09-2024 04:31:44 PM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/195293d2-1a9a-4ad7-94b5-035d59df26ed)

**Comment by dni** [comment]
> Also gets rid of this error where web app should revalidate my liquid address when I am switchin to Liquid: [Screencast from 01-09-2024 04:31:44 PM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/195293d2-1a9a-4ad7-94b5-035d59df26ed)

unrelated opened a new issue

**Comment by dni** [comment]
```ts
        try {
            const assetName = asset();
            decodeAddress(assetName, address);
            input.setCustomValidity("");
            input.classList.remove("invalid");
            setAddressValid(true);
            setOnchainAddress(address);
        } catch (e) {
```
i dont like it, in 99,9% people will choose the asset first and then paste. maybe even people will be confused and trying to send liquid to a btc address and not noticing that the asset magically switched to btc, expecting lbtc to receive.

either why i think this optimisation is too much

**Comment by kilrau** [comment]
> either way i think this optimisation is too much

It is not, I am 100% convinced we want to do this. You don't know the support cases that Michael and I handled where we explained folks to switch the asset to Liquid "because it said invalid address". I see virtually no chance of anyone pasting an liquid address expecting to use mainchain.
