### ISSUE TITLE
Normal Swaps: Disable "Create Invoice via WebLN" button when amounts are invalid

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#380]
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/71f24af3-5f25-4c14-8b30-a8800fe08818)

**Comment by dni** [comment]
why you can just enter the amount then as if you just past an invoice, it will get then set automatically

**Comment by kilrau** [comment]
> why you can just enter the amount then as if you just past an invoice, it will get then set automatically

Only for amount `0` then fine leave it enabled for this, but for all other values out of min/max disable the button please since it unavoidably leads to an error state.

**Comment by kilrau** [comment]
Summary: leave it enabled for default 0 state as here alby let's me choose an amount

![Image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/41916bd3-348c-47cc-ab31-aea99799101a)

but disable for all amounts that are not 0 but outside of min/max range as here the anmount is fixed in Alby and the invoice is guaranteed to not be accepted by web app

![Image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/99adfaec-90c9-46c1-b0b1-28221cb56169)
