### ISSUE TITLE
History: Delete button right aligned

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#386]
Super low prio, but if these `Delete` button would align to the right that'd be awesome visually. Either via solely button right aligned but that could look weird. Best with a fixed width for swap ids and date.

![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/15eeaf52-b48f-4c69-b171-670cb9c9249b)

Also, can we use a nicer arrow to signify the swap direction?

**Comment by anishyadavv** [comment]
i want to work on this

**Comment by michael1011** [comment]
This was already fixed in https://github.com/BoltzExchange/boltz-web-app/commit/2a5ee537baae4f795e2b89d4978b2ee3f8646508

**Comment by kilrau** [comment]
> Also, can we use a nicer arrow to signify the swap direction?

You can add a nicer arrow if you want @anishyadavv

**Comment by anishyadavv** [comment]
Sure @kilrau but, I am having trouble in runnig project locally. It gives me error of dist/404.html file does not exists. Help me in this case
