### ISSUE TITLE
Tests: Refund file download

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#399]
Test refund file download json & qr code, ideally with FF & Chrome on Desktop and Mobile each. Not a small feat since currently our tests use a stubbed dom, not an actual browser.

**Comment by dni** [comment]
we could setup a test suite for integration tests with: https://webdriver.io/ seems a lot of work though, but could be nice.

**Comment by kilrau** [comment]
Superseded by https://github.com/BoltzExchange/boltz-web-app/issues/525
