### ISSUE TITLE
Refund: Liquid address validation fails

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#405]
Several cases today where folks can't refund because the button doesn't turn active, it is a valid address e.g. `VJLAbpeBXnEgfbeUZMzXRYFuxmLsPfM4g4DJp38TZ3iJwjEcComzBJbxK1vtHCXLEgEAHKbgbE9ZYwVi` and in the regular swap box they are recognized as valid
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/1ea5292c-24e4-4ed5-83f7-7ca2d3f7f051)

**Comment by michael1011** [comment]
closed by https://github.com/BoltzExchange/boltz-web-app/pull/406
