### ISSUE TITLE
Clickable min/max amounts don't work in certain states

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#442]
Once I have a 0 or `null` amount either in the send or receive box, I constantly manage to get into states where:

- [ ] I click the min or max amount and it doesn't get populated in the field:

[Screencast from 01-10-2024 10:55:24 AM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/f06fe3a4-4c61-48d8-9a16-9de5e92f8485)
[Screencast from 01-10-2024 10:56:23 AM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/d73286f3-6a46-4e2f-bf6c-9c035477adfd)

- [ ] Or it gets populated but the swap box doesn't re-calculate the second amount:

[Screencast from 01-10-2024 11:00:30 AM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/8da2ce54-c182-4b6f-b469-db60b2a7e2cf)

Nothing in console log.

**Comment by kilrau** [comment]
Especially web app not reliably re-calculating second amount is pretty bad, throws undefined no matter what I do afterwards.

[Uploading Screencast from 01-10-2024 11:06:33 AM.webm…]()

**Comment by kilrau** [comment]
Especially web app not reliably re-calculating second amount is pretty bad, throws undefined no matter what I do afterwards.

[Screencast from 01-10-2024 11:06:33 AM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/46423517-57bb-47c4-a87e-909cb5660943)

**Comment by dni** [comment]
sorry, can you try it again? i cannot reproduce this at all, it may have been fixed in a refactor...

**Comment by kilrau** [comment]
Looks like, couldn't reproduce.
