### ISSUE TITLE
Enforce BOTH amount boxes were calculated & populated before resolving any LNURL/LNADDRESS

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#443]
Enforce BOTH amount boxes were populated with calucalated amounts before resolving any LNURL/LNADDRESS. Right now web app can get into states where it resolves lnurl/lnaddresses to invoices if only one amount is set. That's dangerous since it's not clear what amount invoice has. 

Requirement that this is rock solid before we do https://github.com/BoltzExchange/boltz-web-app/issues/441

**Comment by dni** [comment]
this is solved by https://github.com/BoltzExchange/boltz-web-app/pull/500
