### ISSUE TITLE
Selecting rootstock causes `undefined` states

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#447]
E.g. here the placeholder. Can be easily reproduced by selecting rootstock, then liquid on https://testnet.boltz.exchange/.

![Screenshot from 2024-01-12 17-13-22](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/8c5492a5-72e1-49c3-99dd-0792e8745766)

**Comment by dni** [comment]
fix on main
