### ISSUE TITLE
Create Button: WASM error should supersede all other errors

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#448]
`PLEASE ACTIVATE WEBASEMBLY IN YOUR BROWSER` button should be highest prio error superseding all other erros. As of now, first it asks me to enter amount,
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/7450a01a-016c-40e8-9ead-4beac26009a7)
then a correct address,
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/22e71891-07d1-485d-b1ad-83e3cbd87a9a)
 just to find out it doesn't work in the end.
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/92670ccd-daf8-41a2-bb9d-20be484c3bc9)

**Comment by dni** [comment]
this is solved, wasm is now its own page not even showing the create or refund forms
