### ISSUE TITLE
Error tool tip for pasting amounts above max

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#451]
Currently we don't allow pasting amounts like `1.25` in BTC denom or `125000000` in sats denom. We need some sort of feedback why pasting doesn't work. OR allow pasting them with a much higher limit.

**Comment by kilrau** [comment]
I'd prefer allow pasting large decimal numbers up to  21 million. BUT
- autoconvert `,` to `.` when pasting, see https://github.com/BoltzExchange/boltz-web-app/issues/468#issuecomment-1931824555
- `Clipboard contains invalid characters` tooltip error when pasting sth like this: only numbers `,` & `.` should be allowed. Need to double check filters. ![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/15f034b8-fbfe-49db-acc7-0e96f50219e0)

**Comment by dni** [comment]
> autoconvert `,` to `.` when pasting, see

that sadly does not work very well, you cant mess with the users pasted content, i think the a browser security feature.

the pasting was covered by https://github.com/BoltzExchange/boltz-web-app/pull/496

**Comment by kilrau** [comment]
Closing here since the pasting issue itself is done and the `,` / `.` is covered in https://github.com/BoltzExchange/boltz-web-app/issues/468#issuecomment-1931824555
