### ISSUE TITLE
Refund: Add intermediate redirect page if swap is still in progress

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#470]
When uploading a refund file of a swap that isn't expired yet, we currently just jump to the swap progress page. The idea is good, but that's a big sus - we  have a "This swap is still in progress, redirecting to swap..." intermediate step to make the user aware why this is happening.

**Comment by dni** [comment]
1. for me its not too distracting to switch immedialy

2 possibilites that came to my mind.
 
- a notification popup like we have for other things with `This swap is still in progress, redirecting to swap...`
- show a button, `Swap found in localstorage, click here to open`

**Comment by kilrau** [comment]
> `Found swap in Localstorage, click to open`

Too technical.


> 1. for me its not distracting to switch immediatly

? The point of this issue is to have a separate page that says  "This swap is still in progress, redirecting to swap..." after one pressed "Refund". Better than a notification popup as these are notoriously overlooked.

**Comment by dni** [comment]
so how long should we show the redirect page?

**Comment by kilrau** [comment]
"This swap is still in progress." Button: "Open Swap"
