### ISSUE TITLE
Add subtle loading animation

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#491]
On the other side of the planet, even with an okish internet connection, this loading screen is up for 10s or more if the site is not cached. Let's add a subtle animation to signify the page is loading, e.g. subtle logo beat  - zoom in/out.
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/f55aa052-9d64-4ba3-bb79-ef0011749abc)

**Comment by dni** [comment]
like like the subtle scaling up and down of the logo ill go for that

**Comment by kilrau** [comment]
Yes exactly
