### ISSUE TITLE
UNABLE TO CONTACT SUPPORT: Need help recovering funds

### ISSUE THREAD

**Issue by nakoshi-satamoto** [BoltzExchange/boltz-web-app#524]
Sorry for posting this here. But boltz.exchange has no email or way to contact support. The discord was blocking me from signing up.

There was a forced closure, my lightning node is in a corrupted state. details are here https://github.com/ElementsProject/lightning/issues/7162

My channel open with boltz was forced closed. I don't know which side initiated the forced close.

Can someone at boltz confirm if this was a penalty closure or a regular unilateral close? If this was a penalty closure I am requesting assistance in recovering funds. Thank you
chan ID: 831793x2527x0
force close tx ID: e6df69daa0eefd910d871601bbf0e78e838b6396c79601a28dbbf31bb8312591

**Comment by nakoshi-satamoto** [comment]
nakoshi-satamoto@posteo.net

**Comment by kilrau** [comment]
We got Discord, TG, Email (hi@bol.tz), Nostr, Twitter. Will add Email & TG yo our Website's footer for better visibility, the rest is already there.

Emailed you, we'll do our best to help recover your funds.
