### ISSUE TITLE
Fee discrepancy in Web UI

### ISSUE THREAD

**Issue by ok300** [BoltzExchange/boltz-web-app#533]
With 50 000 sat as input, the fee calculation and target onchain amount makes sense.

<img width="494" alt="Screenshot 2024-03-24 at 09 42 18" src="https://github.com/BoltzExchange/boltz-web-app/assets/106775972/23fed684-ad07-4375-b228-347f90afcef5">

Changing the LN amount to 50 001, the Boltz fee is higher (251) but the resulting onchain amount (45 510) remains unchanged.

<img width="502" alt="Screenshot 2024-03-24 at 09 42 33" src="https://github.com/BoltzExchange/boltz-web-app/assets/106775972/5ddd1b44-9532-4217-abce-9b1c87bfbb51">

**Comment by dni** [comment]
hey! thanks for reporting, but this is actually expected we are ceiling down the value to sats range! which sometimes means trhere is a discrepency of 1 sat on the user side.

**Comment by ok300** [comment]
Hey @dni , yes that's why I reported it, because it's not clear which is the intended way to calculate the Boltz service fee:

- `ceil` would always round up, even if the value after the comma is below 0.5
- `floor` would always round down
- a typical `round` would round up what's above 0.5 and round down all else

Which rounding method is the correct one?

**Comment by dni** [comment]
here are the 2 places in the code where we calculate it.

https://github.com/BoltzExchange/boltz-web-app/blob/main/src/utils/calculate.ts#L11
https://github.com/BoltzExchange/boltz-web-app/blob/main/src/utils/calculate.ts#L56

**Comment by dni** [comment]
did that help you resolve that issue?

**Comment by kilrau** [comment]
> did that help you resolve that issue?

@ok300 should we change behavior or good as-is?

**Comment by ok300** [comment]
Thanks for the followup @kilrau , the links @dni included above confirmed `ceil` is the right way.

IMO there are two issues here:
- question: which type of rounding does Boltz use internally. This is clarified by the links above (`ceil`).
- bug report: the Boltz Web UI behavior shown in the screenshot above, which appears to round differently. If the service fees and received amount shown are "estimates", I suppose there is no bug. But if they're meant to be exact to the sat, the issue is still there in the Boltz Web UI.

**Comment by ok300** [comment]
I'm sorry, there was a confusion on my part.

This works as expected.
