### ISSUE TITLE
Arrow Icon

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#585]
All these should use a nicer arrow (check icon set):
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/78776c70-2712-4152-a664-125431f398ad)
![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/2dc46ca7-72a1-41a5-979d-459601f9044a)

**Comment by dni** [comment]
lets, do this after the chain swap refactor, we already touch those there
