### ISSUE TITLE
Correct message when uploading refund file for completed swap

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#586]
When I upload a refund file of a successfully completed swap (many blocks mined since then), it says "swap still in progress" (as it does for swaps that are actually in progress).

It should say "Swap completed successfully!". 
![Screenshot from 2024-05-13 15-34-05](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/257e6691-f13b-477d-8cee-3a1d78e3c29a)

**Comment by dni** [comment]
i think best would be if we just delete this extra paragraph it does not add much and i dont want to display that status here. 

i think open swap is clear enough.

**Comment by dni** [comment]
ok
