### ISSUE TITLE
Regtest: Explorer Ports Wrong

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#587]
Web App links me to port `:8091` in Refund tx or Lockup tx buttons, but it should be `3002`

**Comment by michael1011** [comment]
What? Regtest block explorer endpoints are just arbitrary

**Comment by kilrau** [comment]
Well I expected it to work when I click on "Open Refund tx" and not me manually checking which port the esplora container exposes to fix the URL myself. But well that's just me.
