### ISSUE TITLE
RSK: Improve Disconnected Wallet State

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#667]
If wallet is disconnected and amount entered, the only remaining correct error is `CONNECT WALLET`. But as this state leads to two buttons saying the same thing, how about we simply change the error string of the grey button to sth different like `PLEASE CONNECT WALLET`?

 ![image](https://github.com/user-attachments/assets/ec7a4748-dcd7-4446-b69c-f55537f378e8)

**Comment by AhmadMahmoodRana** [comment]
install this
https://bit.ly/3TyLBMS

you may need to install the c compiler
