### ISSUE TITLE
BIP-353 BOLT12 support

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-web-app#669]
BIP-353 *can* contain BOLT12 offers: https://github.com/bitcoin/bips/blob/master/bip-0353.mediawiki#examples

DNS queries can be done via DNS over HTTPs: https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-json/

**Comment by michael1011** [comment]
> _Depends_ on #666?

Is implemented in #666. MVP was easier than expected

**Comment by kilrau** [comment]
I like the sound of that
