### ISSUE TITLE
Web App "you successfully received" swap amount doesn't match received swap amount

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#693]
For new rsk accounts where RIF Relay sponsored transactions are used, web app reported amount
![image](https://github.com/user-attachments/assets/3915d791-4086-4a3c-82a3-322169d82687)
doesn't match reality
![image](https://github.com/user-attachments/assets/c1d62503-a7fc-4642-9a03-af16bbdb3b46)

**Comment by michael1011** [comment]
Duplicate of #673 and #675
