### ISSUE TITLE
Minor swap box amount issues

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#72]
- [x] pressing "delete" from 0.0005 or 0.005 or 0.00003 etc all goes to 0.0
- [x] CTRL+A any number in btc denomination and typing 0 creates "0.0" (instead of plain "0") whereas typing any other number like 8 correctly creates "8"
- [x] don't paste from clipboard if it contains not-allowed chars
![Screenshot from 2023-05-16 13-13-00](https://github.com/BoltzExchange/boltz-webapp-3.0/assets/16877539/02e84e39-34d6-456c-a9ba-14365b270b0c)

**Comment by kilrau** [comment]
> [ ] pressing "delete" from 0.0005 or 0.005 or 0.00003 etc all goes to 0.0

Not entirely solved but prbly as good as it gets by https://github.com/BoltzExchange/boltz-web-app/pull/287. Closing here.
