### ISSUE TITLE
Invalid Pair Error should disable "Connect Wallet" button

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#723]
In this state, the Invalid Pair error for Anything->Rootstock should should disable "Connect Wallet" button.
![image](https://github.com/user-attachments/assets/eccd8c60-44cd-466e-9f8f-814649580276)
![image](https://github.com/user-attachments/assets/32c26287-93e7-4986-89a9-70d96cc32c47)

Similar: https://github.com/BoltzExchange/boltz-web-app/issues/686

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

    This is what I did:
    Modified the ConnectWallet component to accept an 'isValidPair' prop and use it to conditionally disable the Connect Wallet button when the pair is invalid.

    I also created pull request: https://github.com/BoltzExchange/boltz-web-app/pull/724

    
    > [!CAUTION]
    > Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
    >
    > The fix provided by Latta AI might not be complete and it can serve as an inspiration.

    ---
    This bug was fixed for free by Latta AI - https://latta.ai/ourmission

    If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
