### ISSUE TITLE
Tor mobile shows "invalid refund file" for valid refund QRs

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#766]
Tested on Android and with Refund QRs only
![Screenshot_20241206-143830](https://github.com/user-attachments/assets/6d9fb873-270d-490d-aae2-e4021235a095)
![Screenshot_20241206-143844](https://github.com/user-attachments/assets/c05a3b33-af6c-41b1-97d4-9e33a75ba257)

**Comment by michael1011** [comment]
Can't be fixed because our QR code scanner library uses HTML5 canvas which is not enabled in Tor browsers by default

**Comment by kilrau** [comment]
Right. Then let's throw at least something more helpful like `This browser does not support QR codes"

**Comment by kilrau** [comment]
Closed by https://github.com/BoltzExchange/boltz-web-app/pull/768
