### ISSUE TITLE
Brave Mobile Skips "Download Refund file" Step

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#774]
User reported and I reproduced it. On Brave Desktop it shows as it should.

https://github.com/user-attachments/assets/5a0a0ded-71e4-41cc-b0cc-6f0f0829e40c

**Comment by michael1011** [comment]
Conflicts with #758

**Comment by kilrau** [comment]
> Conflicts with #758

In what way?
