### ISSUE TITLE
[UX Revamp] Refund file download improvements

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-web-app#89]
User feedback:
> a noob user could easily miss this file...

**Comment by armurbalda** [comment]
![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/6b7d3045-3e5f-458e-a4e3-69d9cbe8694f)

**Comment by armurbalda** [comment]
After some debate we decided to have a "Download Refund File" Button on all swap pages in between /createswap and success.

**Comment by kilrau** [comment]
WILL PROVIDE WIREFRAME

**Comment by dni** [comment]
i think this is already covered by https://github.com/BoltzExchange/boltz-web-app/pull/258

**Comment by kilrau** [comment]
Yes, probably. Please leave this open until I had the time to properly think through every page.
